baseURL = 'https://smrtguy.io/'
languageCode = 'en-us'
title = 'smrtguy.io | what, why & how'
theme = 'paper-tui'
enableGitInfo = true
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.JSON]
  baseName = "version"
  mediaType = "application/json"

[params]
  description = "A project garden - what, why & how"
  author = "smrtguy"
  tagline_main = "what, why & how ..."
  tagline_sub = "where all the smrt things happen."
  
  email = "adam@smrtguy.io"
  github = "https://github.com/mradamclark"
  linkedin = "https://linkedin.com/in/aclark000"

[menu]
  [[menu.main]]
    identifier = "ramblings"
    name = "ramblings"
    url = "/ramblings/"
    weight = 1
  [[menu.main]]
    identifier = "tinkerings"
    name = "tinkerings"
    url = "/tinkerings/"
    weight = 2
  [[menu.main]]
    identifier = "demos"
    name = "demos"
    url = "/demos/"
    weight = 3
  [[menu.main]]
    identifier = "readme"
    name = "readme"
    url = "/readme/"
    weight = 4

[markup]
  [markup.highlight]
    style = "gruvbox-light"
    lineNos = true
    noClasses = false
    codeFences = true
    tabWidth = 4
    anchorLineNos = true
    lineNoStart = 1
  [markup.goldmark]
    [markup.goldmark.extensions]
      footnote = true        # Enable footnotes
      strikethrough = true   # ~~strikethrough~~
      table = true           # Markdown tables
      typographer = true     # Smart quotes, dashes
    [markup.goldmark.parser]
      autoHeadingID = true   # Auto-generate heading IDs
    [markup.goldmark.renderer]
      unsafe = true
