baseURL = 'https://www.smrtguy.io/'
languageCode = 'en-us'
title = 'smrtguy.io | what, why & how'
theme = 'paper-tui'
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[outputFormats.JSON]
  baseName = "version"
  mediaType = "application/json"

[params]
  description = "A project garden - what, why & how"
  author = "smrtguy"
  tagline_main = "what, why & how ..."
  tagline_sub = "where all the smrt things happen."
  
  email = "adam@smrtguy.io"
  github = "https://github.com/mradamclark"
  linkedin = "https://linkedin.com/in/aclark000"

[menu]
  [[menu.main]]
    identifier = "ramblings"
    name = "ramblings"
    url = "/ramblings/"
    weight = 1
  [[menu.main]]
    identifier = "tinkerings"
    name = "tinkerings"
    url = "/tinkerings/"
    weight = 2
  [[menu.main]]
    identifier = "readme"
    name = "readme"
    url = "/readme/"
    weight = 3

[markup]
  [markup.highlight]
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
